version: '3'

services:
  postgres:
    container_name: boilerplate-postgres
    image: postgres:13.11-bullseye
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./var/logs/postgresql:/var/log/postgresql
    networks:
      - boilerplate-network

  redis:
    container_name: boilerplate-redis
    image: redis:7.0.12-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass "secret"
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    networks:
      - boilerplate-network

  redis-commander:
    container_name: boilerplate-redis-commander
    image: rediscommander/redis-commander:redis-commander-210
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: default
      REDIS_PASSWORD: secret
      HTTP_USER: admin
      HTTP_PASSWORD: secret
    ports:
      - '6380:8081'
    networks:
      - boilerplate-network

  mailhog:
    container_name: boilerplate-mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - boilerplate-network

volumes:
  postgres-data:
  redis-data:

networks:
  boilerplate-network:
    driver: bridge